# Generated by Django 5.2.9 on 2026-01-27 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.URLField(blank=True, help_text='URL to user avatar image', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('reader', 'Reader'), ('editor', 'Editor'), ('admin', 'Admin')], default='reader', help_text='Blog role: reader (read-only), editor (can create/edit own), admin (full access)', max_length=20),
        ),
    ]
