# Generated by Django 6.0.1 on 2026-04-13 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_userprofile_bio_userprofile_display_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_suspended',
            field=models.BooleanField(default=False, help_text='Suspended users cannot create content'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='suspend_reason',
            field=models.TextField(blank=True, default=''),
        ),
    ]
