# Generated by Django 5.2.9 on 2026-01-27 19:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['slug'], name='blog_catego_slug_fc0bb9_idx')],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=500)),
                ('slug', models.SlugField(max_length=500, unique=True)),
                ('content_json', models.TextField(help_text='Lexical editor JSON format for rich content')),
                ('featured_image_url', models.URLField(blank=True, help_text='URL to featured/hero image for the blog post', null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('scheduled', 'Scheduled'), ('archived', 'Archived')], db_index=True, default='draft', help_text='Publication status of the blog post', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, help_text='When the blog post was published (auto-set when status changes to published)', null=True)),
                ('view_count', models.PositiveIntegerField(default=0, help_text='Number of times this blog post has been viewed')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(help_text='The author/editor of the blog post', on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
                ('categories', models.ManyToManyField(blank=True, help_text='Categories for organizing blog posts', related_name='blog_posts', to='blog.category')),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'ordering': ['-published_at', '-created_at'],
                'permissions': [('can_publish_post', 'Can publish blog posts'), ('can_archive_post', 'Can archive blog posts')],
                'indexes': [models.Index(fields=['slug'], name='blog_blogpo_slug_361555_idx'), models.Index(fields=['author', 'status'], name='blog_blogpo_author__e8757b_idx'), models.Index(fields=['status', '-published_at'], name='blog_blogpo_status_c0e87f_idx')],
            },
        ),
    ]
