# Generated by Django 6.0.1 on 2026-03-25 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogpost_content_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='featured_image_url',
        ),
    ]
