# Generated by Django 6.0.1 on 2026-03-25 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_add_like_count_to_blogpost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='categories',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Category for this blog post', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to='blog.category'),
        ),
    ]
