# Generated by Django 6.0.1 on 2026-04-06 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_comment_recipe_alter_comment_post_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='comments_disabled',
            field=models.BooleanField(default=False, help_text='When enabled, new comments cannot be posted on this blog post'),
        ),
    ]
