# Generated by Django 6.0.1 on 2026-04-13 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_blogpost_comments_disabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image_url',
            field=models.CharField(blank=True, default='', help_text='URL path to category image', max_length=500),
        ),
    ]
