# Generated by Django 5.2.17 on 2026-09-03 21:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_add_category_image_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('permission_denied', 'Permission Denied'), ('rate_limited', 'Rate Limited'), ('email_send_failed', 'Email Send Failed'), ('storage_failed', 'Storage Failed'), ('elevated_error_rate', 'Elevated Error Rate')], db_index=True, max_length=50)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='warning', max_length=20)),
                ('ip_address', models.GenericIPAddressField(db_index=True, help_text='IP address of the client')),
                ('message', models.TextField(help_text='Human-readable message describing the event')),
                ('details', models.JSONField(blank=True, default=dict, help_text='Additional structured data (status code, rate limit threshold, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Security Event',
                'verbose_name_plural': 'Security Events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_type', '-created_at'], name='blog_securi_event_t_825768_idx'), models.Index(fields=['ip_address', '-created_at'], name='blog_securi_ip_addr_0bf826_idx')],
            },
        ),
    ]
