# Generated by Django 6.0.1 on 2026-04-01 22:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0007_add_tags'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DietaryLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=500)),
                ('slug', models.SlugField(max_length=500, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('images', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True, default='')),
                ('prep_time_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('cook_time_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('yield_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('yield_unit', models.CharField(blank=True, default='', max_length=50)),
                ('cuisine_type', models.CharField(blank=True, choices=[('italian', 'Italian'), ('mexican', 'Mexican'), ('asian', 'Asian'), ('american', 'American'), ('mediterranean', 'Mediterranean'), ('french', 'French'), ('indian', 'Indian'), ('middle_eastern', 'Middle Eastern'), ('greek', 'Greek'), ('japanese', 'Japanese'), ('thai', 'Thai'), ('chinese', 'Chinese'), ('korean', 'Korean'), ('other', 'Other')], default='', max_length=30)),
                ('course', models.CharField(blank=True, choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('dessert', 'Dessert'), ('appetizer', 'Appetizer'), ('snack', 'Snack'), ('drink', 'Drink'), ('sauce', 'Sauce/Condiment'), ('side', 'Side Dish'), ('soup', 'Soup'), ('salad', 'Salad')], default='', max_length=30)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to=settings.AUTH_USER_MODEL)),
                ('dietary_labels', models.ManyToManyField(blank=True, related_name='recipes', to='recipes.dietarylabel')),
                ('tags', models.ManyToManyField(blank=True, related_name='recipes', to='blog.tag')),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('amount', models.DecimalField(decimal_places=3, max_digits=8)),
                ('unit', models.CharField(blank=True, default='', max_length=30)),
                ('name', models.CharField(max_length=200)),
                ('notes', models.CharField(blank=True, default='', max_length=300)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='recipes.recipe')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RecipeInstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveSmallIntegerField()),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('content', models.TextField()),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructions', to='recipes.recipe')),
            ],
            options={
                'ordering': ['step_number'],
            },
        ),
        migrations.CreateModel(
            name='RecipeRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField()),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='recipes.recipe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_ratings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['slug'], name='recipes_rec_slug_412256_idx'),
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['author', 'status'], name='recipes_rec_author__29dfd0_idx'),
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['status', '-published_at'], name='recipes_rec_status_22e486_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='recipeinstruction',
            unique_together={('recipe', 'step_number')},
        ),
        migrations.AlterUniqueTogether(
            name='reciperating',
            unique_together={('recipe', 'user')},
        ),
    ]
