# Generated by Django 6.0.1 on 2026-04-06 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='comments_disabled',
            field=models.BooleanField(default=False, help_text='When enabled, new comments cannot be posted on this recipe'),
        ),
    ]
