# Generated by Django 6.0.4 on 2026-07-23 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recipe_comments_disabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='description_text',
            field=models.TextField(blank=True, default='', help_text='Plain-text extract of description, kept in sync on save, used for search/preview'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Lexical JSON format'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='notes',
            field=models.TextField(blank=True, default='', help_text='Lexical JSON format'),
        ),
        migrations.AlterField(
            model_name='recipeinstruction',
            name='content',
            field=models.TextField(help_text='Lexical JSON format'),
        ),
    ]
