# Generated by Django 6.0.4 on 2026-07-23 20:52

import json
from django.db import migrations


def wrap_as_lexical_json(text):
    """Wrap plain text as a minimal valid Lexical JSON document."""
    if not text or not text.strip():
        return json.dumps({"root": {"children": [{"type": "paragraph", "children": [{"type": "text", "text": "", "format": 0}], "format": ""}], "type": "root", "format": ""}})

    try:
        json.loads(text)
        return text
    except (json.JSONDecodeError, TypeError):
        pass

    return json.dumps({
        "root": {
            "children": [
                {
                    "type": "paragraph",
                    "children": [
                        {
                            "type": "text",
                            "text": text,
                            "format": 0
                        }
                    ],
                    "format": ""
                }
            ],
            "type": "root",
            "format": ""
        }
    })


def migrate_recipes_forward(apps, schema_editor):
    """Wrap existing Recipe.description, Recipe.notes, and RecipeInstruction.content as Lexical JSON."""
    from helpers.lexical import lexical_to_text

    Recipe = apps.get_model('recipes', 'Recipe')
    RecipeInstruction = apps.get_model('recipes', 'RecipeInstruction')

    for recipe in Recipe.objects.all():
        if recipe.description:
            recipe.description = wrap_as_lexical_json(recipe.description)
        else:
            recipe.description = wrap_as_lexical_json('')

        if recipe.notes:
            recipe.notes = wrap_as_lexical_json(recipe.notes)
        else:
            recipe.notes = wrap_as_lexical_json('')

        recipe.description_text = lexical_to_text(recipe.description)
        recipe.save(update_fields=['description', 'notes', 'description_text'])

    for instruction in RecipeInstruction.objects.all():
        if instruction.content:
            instruction.content = wrap_as_lexical_json(instruction.content)
        else:
            instruction.content = wrap_as_lexical_json('')
        instruction.save(update_fields=['content'])


def migrate_recipes_backward(apps, schema_editor):
    """Reverse: extract plain text from Lexical JSON."""
    from helpers.lexical import lexical_to_text

    Recipe = apps.get_model('recipes', 'Recipe')
    RecipeInstruction = apps.get_model('recipes', 'RecipeInstruction')

    for recipe in Recipe.objects.all():
        recipe.description = lexical_to_text(recipe.description) or ''
        recipe.notes = lexical_to_text(recipe.notes) or ''
        recipe.save(update_fields=['description', 'notes'])

    for instruction in RecipeInstruction.objects.all():
        instruction.content = lexical_to_text(instruction.content) or ''
        instruction.save(update_fields=['content'])


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_add_lexical_json_fields'),
    ]

    operations = [
        migrations.RunPython(migrate_recipes_forward, migrate_recipes_backward),
    ]
